author: H31IX
database: false
description: Easy pickaxe tool for digging.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.h31ix.excavate.Excavate
name: Excavate
startup: postworld
url: http://H31IX.NET/
version: '1.0'
commands:
  excavate:
    description: Toggle the excavation tool
    usage: /excavate
